### ISSUE TITLE
Beast Boost is not adding onto the right stat on pokemon

### ISSUE THREAD

**Issue by Owski2002** [ObliqueNET/Terra#163]
While testing on single player I was testing with Blacephalon, battling trainers and realised that the beast boost is not increasing the highest stat. Firstly tested with a level 1 where the stats were 12,7,6,8,6,8 and the beast boost increased attack 5 times. Then I tested with a level 100 Blacephalon where the stats were 247,317,142,371,194,313 where the beast boost was increasing speed
![ev 1](https://user-images.githubusercontent.com/34965274/52181291-3c5af280-27e8-11e9-9b39-867754f0f562.png)
![ev 2](https://user-images.githubusercontent.com/34965274/52181292-3e24b600-27e8-11e9-8e6e-2d2c50b3631a.png)
![ev 3](https://user-images.githubusercontent.com/34965274/52181293-3fee7980-27e8-11e9-85dc-29b2c120b663.png)
![ev 4](https://user-images.githubusercontent.com/34965274/52181295-42e96a00-27e8-11e9-8d30-5f8e30478abf.png)

**Comment by Hunter1220** [comment]
Looks like it's been programmed to raise the second highest stat rather than the highest as we can see in both examples that the stat that is being raised by Beast Boost is the second highest stat. If I had to guess this may have been done to make sure the game didn't try to raise HP since it's usually higher than all other stats in certain scenarios but for all I know it could've been a simple error.

**Comment by Owski2002** [comment]
but if that was the way then in the first scenario the spatk or speed would increase

**Comment by Hunter1220** [comment]
Well with that said what I was trying to imply was that it wasn't necessary as the game seems to already exclude HP.

**Comment by Rasgnarok** [comment]
Fixed for 7.0.1
