### ISSUE TITLE
VerifiedVenom's Ban Appeal 

### ISSUE THREAD

**Issue by VerifiedVenom** [ObliqueNET/Terra#207]
Name: VerifiedVenom
Server: Terra
Reason for Ban: Honestly only warning i got was for saying "gay" other than that idk

This is my first time playing on the server and instantly felt disrespected by the staff and after a few minutes playing on the server I see someone change their name to "a young hot loli" which was changed, and I called the staff out for abuse since the user was just trying to have fun. When i called them out for censorship i was called a "troll" and immediately banned. I feel like the staff on this server handled it very unprofessional and the owner should rethink their staff. I even made a github account to say this, now that i got my warning in a form of a ban i understand what i did was wrong, i will not do it again if i could get a second chance that would be great since i never got a first one...

Witness's: Barlex and many other users

Plea: If i cannot be unbanned right away I'll be willing to take a week ban or more/less but not a perma ban since it is first instance of an issue.

Regards, Venom

PS: I was also banned on discord for calling out the staff.

**Comment by Barlexx** [comment]
Though I immensely disagree with the way venom "called out staff" I think the ban was extreme. I think a temp ban of 3-4 days or a month ban from in game chat would have been a more reasonable and beneficial for all parties involved

**Comment by Rasgnarok** [comment]
Barlexx, appeals are for staff to deal with because they have the context the appealing party often omits. IN this case, Venom, you had been warned before for troll messages with explicit language, and you were therefore banned for one last case of it (which was calling my Moderation Admin 'corrupt piece of garbage' when he was trying to get a report of possible staff zealousness). 

Here's an example of your continuous trolling: 
![image](https://user-images.githubusercontent.com/18584380/53855326-24b78b00-3f9b-11e9-9e29-67fce26ee6a3.png)

and here's what got you a ban on discord as well, and a final nail in the coffin:
![image](https://user-images.githubusercontent.com/18584380/53855349-34cf6a80-3f9b-11e9-8c0e-ab6dc6c62b63.png)

**Comment by Rasgnarok** [comment]
As for the reasoning behind _why_ that was wrong, it's fairly simple. Don't be explicit on purpose when there's 12 y/o kids watching. Minecraft is an all-ages game, and we will keep the language as clean as possible while also allowing some leniency. You exhausted that with your repetitive commentary. And by the way, it's not censorship. You don't have rights here, this has nothing to do with the Bill of Rights. You follow the rules we created to allow everyone to coexist, that's the end point of this. 

Feel free to reply if you want to discuss your attitude, if it deserves unbanning, but I won't be debating the severity of your language when you clearly felt like trolling.

**Comment by VerifiedVenom** [comment]
While I see how I was in the wrong I don’t see a warning if you could see a warning as a whole other than not to use gay as insult that would give me more context

**Comment by VerifiedVenom** [comment]
Also how else can I contact you?

**Comment by Rasgnarok** [comment]
My staff was too busy explaining to you why 'ayounghotloli' is not appropriate to issue a ban on the nut comment, among the other ones. You can contact me here, I am all for transparency when it comes to ban appeals. If you'd like privacy, you can join the Pixelmon discord and DM me from there.

**Comment by VerifiedVenom** [comment]
As I stated above I’m banned from the pixelmon discord if you could please end username that would be great and thank you for responding quickly

**Comment by Rasgnarok** [comment]
https://discord.gg/sponge 
Join that one then, then go into your discord Home and find Rasgnarok#6969

**Comment by Barlexx** [comment]
I do apologize Ras, I did not mean to intervene on the matter of staff. I just expressed a response I found would benefit both parties, but that was by no means me trying to declare a solution.

**Comment by Rasgnarok** [comment]
No I understand ya, it's more of me liking to make sure the banned player understands the reason why. Either way, all fine - gotta go in DMs now

**Comment by VerifiedVenom** [comment]
"Don't be explicit on purpose when there's 12 y/o kids watching." as for this comment on your store you stated "Please help Rassie collect enough money to afford a computer where she can actually play games and (tiddy) stream. " which has a picture of your breast covered by melon emoji's how is this appropriate for 12 y/o  kids based on your statement it seems pretty hypocritical of you to say... i also have photo evidence of said page for proof just in case you take it down.

**Comment by Rasgnarok** [comment]
It is amusing how you were just given a second chance by DMing me, then proceed to assume the worse. I could have discussed the difference I see, but since you clearly expect the worse in people, I won't waste my time clarifying it for you.

As for the obvious meme, I would never dare delete it - how else would I then be called a hypocrite? Gotta leave people like you something to complain about, after all.

**Comment by VerifiedVenom** [comment]
F
