### ISSUE TITLE
Quests that require gyms not registering

### ISSUE THREAD

**Issue by Qwayne** [ObliqueNET/Terra#210]
The monarchs labyrinth and merciless quests haven't registered my gym progress.
![Screenshot (87)](https://user-images.githubusercontent.com/48507414/54258422-0134a780-457c-11e9-9b63-1d5e77ac40b8.png)
![Screenshot (88)](https://user-images.githubusercontent.com/48507414/54258423-0134a780-457c-11e9-9f4d-701d866fe1da.png)
![Screenshot (89)](https://user-images.githubusercontent.com/48507414/54258424-0134a780-457c-11e9-87c6-d28458fd7722.png)

**Comment by Rasgnarok** [comment]
I'll forward to the QDs, they'll update this ticket.

**Comment by Soul3are** [comment]
Hello, 
The quest, "Monarchs Labyrinth" has had its gym requirement in order to start, removed. This has been done with all the other quests with the exception of, "Merciless" as the only one that still needs it gym requirement removed. If you are still having trouble starting it, a quest designer who is online should be able to restart you, so you can start it successfully, now that the requirement has been removed.

**Comment by Vohras2** [comment]
Closing this for now, since the quests have reset to the new ones without Gym Requirements. Let us know if this is an issue in the future.
