### ISSUE TITLE
Googooinga here. I am a goofball! :D

### ISSUE THREAD

**Issue by Reedtard** [ObliqueNET/Terra#250]
I was gaming on Terra with the boys, and my friend said something, and I replied "Shut up fag". I am sorry for loosely slangin around that offensive word. I promise I will do my homework Dad. Thank you for your time. (P.S.) I have cool guy syndrome.

**Comment by ElementalMP** [comment]
I've looked over this event, and I'm willing to view this as an instance of emotions getting in the way of judgement. As such, I have unbanned your account. Please keep in mind second chances do not come by often, and in future, when a staff member asks that a topic be dropped, it is best just to leave it be in order to stay out of trouble.
