### ISSUE TITLE
(Ban Appeal)

### ISSUE THREAD

**Issue by Diamondsx64** [ObliqueNET/Terra#255]
I was forced to move because i had built to close to someones base by accident then i was given a compromise of some pokemon + money and i left after i had finished moving i got really salty because of how much time it took and went back to the original location of the base and placed dirt everywhere and made it look ugly, i now regret it and was hoping i could come back to the server.

**Comment by ElementalMP** [comment]
As far as I know the shinies and money were a deal in which you accepted happily. Several of the staff helped you move your base, not because they had to, but as a gesture of goodwill. You say that you griefed because of how long it took, despite every effort was made to make it as short as humanly possible. Not only did you place dirt, you obliterated the entire area, entirely out of spite. You were thoroughly compensated for having to move, you knew that what you were doing was wrong, and you did not apologize for your actions. Because of this, you will stay banned.
