### ISSUE TITLE
Ban Appeal - ASMRFoodReviews

### ISSUE THREAD

**Issue by Zestii** [ObliqueNET/Terra#272]
IGN - ASMRFoodReviews

I received a ban on Terra about 20 minutes to half an hour ago, the ban was unwarranted and false. Although it was breaking rules (Did not know at the time) I claimed an unclaimed base, a moderator named "CenizaRey" froze me after I was told the owners of the base were online and teleported there. I was then made aware of the rule (Checking myself with /rules) but was never explicitly warned that my action would result in a ban. I asked if I could receive pokeballs in exchange for my unclaiming of the land. This was all in public chat so a user requested to teleport to me, not sure how he/she is involved prior to the teleport request, and gave me x116 Ultra Balls, At this point I, with having difficulty, was told the command to unclaim. I proceeded to unclaim the land and leave the base. I was later told I made a mistake and that I'd "regret" it due to my now supposed bad reputation on "the biggest pixelmon server." I then said "It was good doing business with you :^)" and using the expressive face ":^)" as just a simple way to declare my content attitude after the exchange. It was perceived as "disrespectful" and I was given a ban for reason "The Ban Hammer Has Spoken." I'm just appealing this ban as the circumstance was rather one sided and I was not given any warning being told I would get banned if I didn't unclaim. I was banned nonetheless and I'm quite upset about this. My biggest mistake in the situation was not understanding the rules from the get-go and I apologize for that. Thank you for taking your time to read this and I hope this issue is resolved soon.

**Comment by CenizaRey** [comment]
Let's break this down.

So, the first thing you responded with when asked to unclaim the area was "What will I get out of unclaiming it". Which is, right off the bat, a poor impression. After then spewing out 29 pieces of coal and a PC which were stolen from the base you priorly claimed over, I found out you had stolen several other items which you failed to take inventory of when emptying your inventory of the evidence.

So after much difficulty and explanation that you can't just claim over what isn't yours, and after your protests stating "Get a more important staff member", you begrudgingly unclaim the area after multiple warnings. Stating that all you wanted were some pokeballs. Which, as you mentioned, a good samaritan gave to you. I then send you to spawn, twice, so you can't /back. You then hit us with a "nope" and you warp to the home you set in the base you claimed over. So I am then forced to delete that home. 

I then watch you leave the base, chasing and punching another player as you go. In chat you're still fanning flames, saying "It was good doing business with you :^)" to the people you claimed over, as well as "I got what I wanted :^)", as if _proud_ of the fact you caused bother to other players.

You stood your ground fully aware of the fact you were making a poor impression on the community saying "This is pixelmon" "I don't play it to get involved with the community". Although I'm paraphrasing, I know I got the gist. I would respect your decision to opt out of the community, if you didn't subject the rest of our playerbase to your horrendously antisocial behaviour.

Your attempts to cover up your blatantly smug and self-important attitude by referring to it as a "content attitude" layered on top of the fact you are complaining about the nature of your ban message ultimately results in the conclusion to anyone with a brainstem that you yourself know you don't have an argument here. Tl;dr, You joined Oblique Terra, broke numerous rules, and you didn't give a shit about any of them until you got banned.

**Comment by Zestii** [comment]
I'd appreciate if a different, more non biased staff member could read the appeal. Someone who could read the logs and determine it themselves. Don't get me wrong I'm sure you're a well respected and good moderator but this is a situation involving you and your bias towards it shouldn't be the determining factor. I recognize that I made a mistake and also If anything else was stolen from the base it was not from my doing as others, which I will only name if I must, were trusted in my claim. Also my "hoes mad" comment was obviously in reference to the song and was an attempt to lighten the situations tension by citing a comedic and current meme, I understand it could've been taken the wrong way but that wasn't my implication. Perception is obviously a large issue in this instance and I apologize for my "antisocial behavior" but I never intended to have a negative impact on the situation and "blatantly smug" was not what I was going for. Once again apologies for the inconvenience and if you'd like the chance to talk it over in a more conversation-like setting you can add me on discord (your lover#9515)

**Comment by Rasgnarok** [comment]
I respect Ceniza's perspective since he is, by all means, the 'arresting moderator'. Elemental or I will review the information provided by both, and issue a statement. Communication is key in ban appeals, and it seems it would have been an excellent attribute prior to the ban as well. We will be responding within the next day.

**Comment by ElementalMP** [comment]
It would appear I am the one to review this, then. 
After looking at all the logs, and recounts of this event, I have come to the conclusion that while the way this ban was issued could have been better, the grounds on which it was issued was pretty on point. 
You start by telling one of the helpers that you, and I quote, "didnt take nothing". This is obviously not the case, as you took multiple items from the base. Before Ceniza has even intervened, you are already lying to the staff attempting to resolve the issue. 
Following this, multiple staff members and several members of the public had to ask you to unclaim before you even attempted to do so, with you asking how to unclaim after multiple instances of you arguing why you should even do so, despite being informed that you were breaking rules. 
You claim that Cen should "Get a more important staff member", or the ban will be for nothing? All moderators have the power to unclaim things that shouldn't be, and I am unsure what would bring someone to believe that a Sr. Moderator would be lacking such an ability? 
Finally, on your way out of the base, you are attacking players. If you had read the rules, or even just rule 4 you would know that you should not grief or steal, and also that you shouldn't PvP without consent. This is seen below. 
![image](https://user-images.githubusercontent.com/31155918/57838705-56f62c00-7819-11e9-8366-96fd54e672ee.png)
By PvPing these randoms, all you have done is display that you either 1. Didn't read the rules, and are blatantly lying to both myself and a moderator, or 2. You didn't care what the rules were, and just wanted to rebel against the staff. In either case, this is the final nail in the coffin for this ban. Because of this, I will not be revoking this ban. As you stated, you are not here for the community, but the mod itself, I do hope that you continue to enjoy Pixelmon in singleplayer, or on another server.
