### ISSUE TITLE
ItzChkn Ban Appeal

### ISSUE THREAD

**Issue by LowIQDuck** [ObliqueNET/Terra#332]
I admit to griefing and lying to the staff and I'm really sorry about it. If I get another chance I will not grief anymore and I will gladly return the items I stole and will give the person I stole from all of the in-game money I have an I have about 10500.

**Comment by Rasgnarok** [comment]
Your victim has already been refunded, but it's nice of you to offer. What I do not understand however, is why you would lie about breaking the rules. The only reason you were permanently banned, instead of temporarily banned, is because you lied when staff asked you about your connections to a raid.

**Comment by LowIQDuck** [comment]
I don't know either why I lied. I just did it because it didn't know what to say. I won't lie anymore to the staff if I get unbanned.

**Comment by Vohras2** [comment]
This hasn't had any updates in quite a while. Feel free to reapply if you are still interested.
