### ISSUE TITLE
i got banned on terra for xraying....and i regret it

### ISSUE THREAD

**Issue by TomahawkYT65** [ObliqueNET/Terra#364]
Ban Appeal i wish i never hacked cause terra was the only server i really enjoyed and played can i please get unbanned it will never happen again i dont care if i get wiped just please unban me trust me ill never try to xray anything EVER again.

**Comment by TomahawkYT65** [comment]
or hack ever again on minecraft

**Comment by TomahawkYT65** [comment]
my username is TomahawkYT

**Comment by TomahawkYT65** [comment]
someone pls respond to my ban appeal

**Comment by ElementalMP** [comment]
I honestly do believe that you regret using a hacked client. Despite the fact that your last ticket was closed, I'm willing to allow you back on the grounds that you are careful not to break any other rules, and that you agree to having you account reset; since I cannot determine what is legitimate and what is not. If you are happy with this, I can unban your account :)

**Comment by TomahawkYT65** [comment]
thank  you  so much <3

**Comment by TomahawkYT65** [comment]
im happy with this

**Comment by TomahawkYT65** [comment]
wait will my pokemon stay either way if i lose them i can just look for somemore

**Comment by TomahawkYT65** [comment]
and also i agree to having my account reset

**Comment by ElementalMP** [comment]
I'll have to reset everything, I'll sort it when I am at my desk, shouldn't be too long :)
