### ISSUE TITLE
[Landlord]

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Terra#372]
Landlord denying messages as players can open chests (meaning there's either two interacts firing, or something else is being denied as they are allowed to interact). Gets annoying.

**Comment by Valjean42** [comment]
is this in EVERY claim, or only in admin claims? (I dont even know if this is still relevant :P )
If only in admin claims, it's because of one line i found:
![image](https://user-images.githubusercontent.com/47981683/69448711-d3863c00-0d61-11ea-9b93-5f2739f577f6.png)
and thats because some quests require you to take stuff from chests if im not mistaken (one that comes to mind is "Under the sea" with the mega sharpedo)
if its not only in admin claims, ill try to debug it in a bit

**Comment by Valjean42** [comment]
I changed an "if" line's order to not show the message if it lets the chest open, committing that to the code right now. if that was the problem im pretty sure this issue can be closed.
