### ISSUE TITLE
Ban apeal

### ISSUE THREAD

**Issue by carn6ge** [ObliqueNET/Terra#380]
i wish to be unbanned i admit to using a hacked client i would accept to be banned for 1 or 2 weeks and then be unbanned and i accept if thats not gonna happen ign: Carn6ge

**Comment by ElementalMP** [comment]
I am unsure why you would be under the impression we would be okay with usage of a hacked client 
on the server. It's specifically stated in the rules, as well as just being common sense. It is quite clear that you don't have any respect for the rules of the server, and it's also pretty easy to see that you don't really feel bad about it. Unbans are for people that regret what they have done, not those that want to try their luck at a second chance because they think they can.
