### ISSUE TITLE
Issue With Life and Destruction, A Pure Heart, and A Blank Mind

### ISSUE THREAD

**Issue by HeroAtHeart** [ObliqueNET/Terra#383]
On the wiki, it says that, to do A Pure Heart, you need to complete Life and Destruction. It also says you need to complete A Blank Mind before Life and Destruction.
The issue arises when you look at the actual quest guide using /quests. First off, the quest point requirement for Life and Destruction is different than it is on the wiki. (Wiki=100, Quest Log=130).
The next issue is that the Quest Log says you need to complete A Pure Heart before you can start Life and Destruction, when according to the wiki, you should need A Blank Mind for it.
The other issue is that the wiki says you need Life and Destruction for A Pure Heart, but in the Quest Log, that's not a prerequisite for it.

**Comment by MattBlower** [comment]
Yeah the wiki wasnt updated after the reboot. When I originally wrote the quests it was A Blank Mind > A Pure Heart > Life and Destruction, but due to issues Life and Destruction ended up being released first. With the reboot I corrected it back to the right order, but the wiki was never updated to match.

**Comment by Vohras2** [comment]
Closing this because I assume it's been updated? The quest lore changes will make this easier to see.
