### ISSUE TITLE
Real mature.

### ISSUE THREAD

**Issue by HyperWilson** [ObliqueNET/Terra#395]
Your making yourselves look bad, don't you understand? It doesn't matter if you think i'm a griefer or not. It's a video game. Don't act so smug and self-assured because your an admin of a minecraft server.
It doesn't matter if you think i'm a griefer, i know i'm innocent, i won't try to change your mind.
Thanks for proving my point by the way, i knew ahead of time that this wouldn't be received well at all, nobody can consider the mere possibility that something like this CAN happen.

Speaking of which, it's rather funny that you'd either have to delete this, or silence everyones speech by locking a thread. Real mature.

Try to be a bit more "positive", alright? I've shown nothing but courtesy and class here, and i will CONTINUE to.

**Comment by HyperWilson** [comment]
And before you ban me, think about it. If you silence/ban me, it means your AFRAID of what i have to say. Making you all look worse.

**Comment by HyperWilson** [comment]
I'm sure plenty of the players on this server (Including Soxiel) are quite tired of this shit. Let my threads be unlocked. Those with half a brain can decide for themselves rather than being spoonfed by administrators who think their all top-shit for holding powers over a video game server.

**Comment by Hiroku** [comment]
You: "I want a statue built in my honour"
Also you: "It's just a Minecraft server ha ha ha"

You: "If you silence me, it means you're* afraid of what I have to say"
Also you: "Someone somehow used my IP! I'm innocent! I don't know how it happened!"

Reason why you're getting banned from this tracker is because you keep making tickets where you attempt to profess innocence and righteousness when you got caught like an absolute muppet. I'm quite happy for you, and whoever somehow believes you, to leave. We'll see how long you remain on Limitless.  The owner of Limitless and I made the mod, so I'll get him up to speed real quick.
