### ISSUE TITLE
Banned 22.11.19

### ISSUE THREAD

**Issue by MonroeTheOger** [ObliqueNET/Terra#409]
The day being Friday I was attending a party from 18:00-22:32. During these times I had left my computer on. Once finally hoping onto my computer again I realise the fact that I've been tp’d to a ‘’prison’’ of some sorts. I start saying : [16:32:27] [Client thread/INFO]: [CHAT] [Poke] Deepshet: admin abuse? [16:32:29] [Client thread/INFO]: [CHAT] [Poke] Deepshet: what 

I then proceed to wash myself. Taking a shower etc. Once coming back I realise that fact that I've been banned for ignoring staff. Later seeing the logs it appears the admin wickedshadow had been trying to contact me.  

[16:32:47] [Client thread/INFO]: [CHAT] [Me » Deepshet] Can you accept no more raiding places [16:33:08] [Client thread/INFO]: [CHAT] [+] Hannes_steel (I was in the shower during this time) 

As you can see from the timestamps I was banned within a 30 seconds. Time goes by and I proceed to contact wickedshadow, this is where he introduced me to the claim of me raiding unclaimed bases. I ask him about his sources he tells me that he himself doesn’t have any proof of this claim.  

 
![Proof](https://user-images.githubusercontent.com/58092311/69468633-2de8c200-0d8d-11ea-8091-e77d643ea912.PNG)

Later going I explain to him that two of my friends had joined the server. Spookyseagulls and Jonnaval. Both these indivuals had gotten a start from our friend Get__Punished. Me, I offer them to come share bases with me, so we decide to move loot. Jonnaval who was tested regarding this information suffers from an Alzheimer disease (wich I don’t know too much about) Spookyseagulls was simply not online at the time of this event but joined at the end. At this point wickedshadow refused to test spookyseagulls and went offline.

**Comment by ElementalMP** [comment]
Hiya, thanks for being so patient. From what I understand, a moderator found a base belonging to your friend, who also mistakenly took said base from an older, unrelated player, and this whole thing is a misunderstanding due to seeing you taking items from his base and mistakenly believing you to be raiding it. Is that correct?

**Comment by Monroe81091** [comment]
Yes, that is correct

**Comment by ElementalMP** [comment]
Ah, okay. What doesn't make sense, then, is the other bases that show you and your mates taking items from them. Since you've said that the one base claimed by your friend is the only one involved, it would seem to me something isn't adding up. Any theories? I have one or two, but I'd like to hear your side of things.

**Comment by ElementalMP** [comment]
I'm gonna go ahead and assume you don't plan on answering this. Have a nice day!
