### ISSUE TITLE
Unclaim Issue

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Terra#410]
Roku Told me to put a bug report up with this.

[blob:https://imgur.com/23c37681-7d1f-472b-847c-0e1ddd46c9b7](url)

**Comment by Valjean42** [comment]
Uhh it doesnt let me see the picture, can you try to get a better link or something? :P

**Comment by Hiroku** [comment]
The issue is this:
/unclaim with a radius, in a player claim that is not his own, says he doesn't have permission regardless of the actual permission nodes he has.

**Comment by Valjean42** [comment]
i assume it's because of this line:
![image](https://user-images.githubusercontent.com/47981683/69477052-4b984480-0dea-11ea-8544-75914f4928b8.png)
the function only checks for whether the claim's owner is the user (allowed to manage claims function returns true ONLY if the player is the claim's owner), and does not check if the user of the command has any overriding permissions

**Comment by Valjean42** [comment]
i suggest changing the line to something like this:
![image](https://user-images.githubusercontent.com/47981683/69477145-3d96f380-0deb-11ea-858e-5fd763f9cda6.png)
Considering i dont know the exact permission needed (cant find it for some reason) i leave that to hiro

**Comment by Hiroku** [comment]
I think the appropriate node is probably landlord.admin.command.unclaim

**Comment by Valjean42** [comment]
ok so i changed the line to:
![image](https://user-images.githubusercontent.com/47981683/69481047-418c3b00-0e16-11ea-88c9-7eaf2e2d9312.png)
and that makes it so /unclaim with a radius unclaims ALL claims in the radius, which is probably not the wanted outcome, so im gonna try to think of a wanted outcome and change the code accordingly

**Comment by Vohras2** [comment]
I think this has been fixed, but we'll see. Closing for now.
