### ISSUE TITLE
Lads on their way to ban Bobby for like the 218th time oh yeah

### ISSUE THREAD

**Issue by Austinator** [ObliqueNET/Terra#447]
Hey what's going on big man or woman reading this I was banned and it said to go here if I feel its wrong and so look at that I have arrived.
Was I banned on accident in some mix-up again or was I the dude doin smthn.
If I was doin something you should give an in-depth explanation of what I have done to deserve the permban so that I may rebut said reasoning thank you.
Also if it is the latter you should explain to me in some Discord dms for my convenience if that's acceptable. Thanks again man cool.

**Comment by ElementalMP** [comment]
Honestly man, I would have thought the reasoning pretty clear. You've made it your mission for years to skirt the rules here, slinging off at anyone you think you can get away with slinging off at, only to try and twist your words into something seemingly innocent whenever someone of some real power shows up. You argue mindlessly with those who stand up to you, and harass those that don't. 
This game of cat and mouse has been going on for so long, and honestly we are all sick of it. You've had hundreds of second chances, and every time you say that it's unjust, because you have gotten better. We've come to notice that while you are "getting better", what you are really doing is just enough so you can skirt the line all over again. Ras, Hiro, Admiral, I, and many others have all stuck their neck out for you, and you spit in our faces every time.  
Because of this, and because of the way you choose to treat the rest of our server members, you will not be unbanned.

**Comment by Austinator** [comment]
Okay but no.
If my 'mission' here was to skirt the rules and antagonize others and shit you'd think I'd be constantly and conscientiously doing that. Even when I go out of my way to say no that is not what I'm trying to do you still take it as that, you're making my statements absolutely irrelevant just because you don't want to believe them. I do not 'sling off' at anyone unless they whippin out at me or if I'm joking around in which case I will blatantly state that I am joking to try to avoid misunderstandings such as this, saving the both of us a good chunk of our time. You say I twist my words even though I restate them exactly as before with slight word alterations to make it more easily understandable, it is not up to you to tell me what I intend to say. You need to understand that you do not know how everyone's minds work and that some people spew information out in different ways than others, sometimes resulting in strings that you consider malicious but are not to the other party. You tell me I argue mindlessly with those who stand up to you, but I am currently arguing while bringing up points I believe to be reliable in this circumstance against someone who has taken an action I do not agree with, as such of every other argument I've taken part in here. You say I harass people who don't stand up to me but I have harassed absolutely nobody in my time here outside of jest. You tell me all these negative things about what I've done with absolutely no examples supporting these thoughts. This game of cat and mouse has indeed gone on for too long, it would really be great if time could be spared and staff would stop chasing me for every minor thing I do that they think they can start a witch hunt out of. We both know that the entirety of staff has to be told to drop nearly every single hunt revolving around me, yet they still continue to pursue at even the smallest passive action I take. Those hundreds of chances you say were given to me were extremely unrealistic, expecting me to be completely silent so staff doesn't get off on me the second I say "The". I say all past times were unjust because well Ras agreed that they were, so that means they probably were. If the comment I was banned for was made by any other player it would've been ignored, but since I made it I wasn't even given time to explain and got banned. This is not fair and in my eyes is an example of a witch hunt, which Ras says she defends me from, although not this one apparently.
Because of these thoughts, I believe I should not have been banned in the first place, and that is should be repealed. Thank you.
